name: thousand_melochey
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.0
  auto_route:
  get_it: ^7.6.7
  freezed_annotation: ^2.4.1
  flutter_multi_formatter: ^2.12.4
  dio: ^5.4.1
  proste_indexed_stack: ^0.2.4
  connectivity_plus: ^5.0.1
  internet_connection_checker_plus: ^2.2.0
  requests_inspector: ^3.4.1
  pinput: ^4.0.0
  slide_countdown: ^1.6.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  firebase_core: ^2.30.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  auto_route_generator: ^7.3.1
  freezed: ^2.4.7



flutter:

  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

