name: thousand_melochey
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.0
  auto_route:
  get_it: ^7.6.7
  overlay_kit: ^1.1.0
  freezed_annotation: ^2.4.1
  flutter_multi_formatter: ^2.12.4
  dio: ^5.4.1
  proste_indexed_stack: ^0.2.4
  connectivity_plus: ^5.0.1
  internet_connection_checker_plus: ^2.2.0
  requests_inspector: ^3.4.1
  pinput: ^4.0.0
  slide_countdown: ^1.6.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  firebase_core: ^3.9.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  flutter_localization: ^0.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  auto_route_generator: ^7.3.1
  freezed: ^2.4.7
  flutter_gen: ^5.8.0


flutter:
  generate: true
  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/font/Comfortaa-Regular.ttf
    - family: Comfortaa-Medium
      fonts:
        - asset: assets/font/Comfortaa-Medium.ttf
    - family: Comfortaa-Bold
      fonts:
        - asset: assets/font/Comfortaa-Bold.ttf
    - family: Jura
      fonts:
        - asset: assets/font/Jura-Regular.ttf
    - family: Jura-Medium
      fonts:
        - asset: assets/font/Jura-Medium.ttf
    - family: Jura-Bold
      fonts:
        - asset: assets/font/Jura-Bold.ttf


